### ISSUE TITLE
performance?

### ISSUE THREAD

**Issue by tomByrer** [fabiospampinato/json-sorted-stringify#1]
Have you tested this vs native?

**Comment by fabiospampinato** [comment]
Native as in `JSON.stringify`?

I get the following with this module:

```
> json-sorted-stringify@1.0.0 benchmark
> tsex benchmark

small → 46µs
medium → 614µs
large → 2045ms
Ran 3 of 3 in 2045ms
```

And the following with `JSON.stringify`.

```
> json-sorted-stringify@1.0.0 benchmark
> tsex benchmark

small → 0µs
medium → 123µs
large → 884ms
Ran 3 of 3 in 884ms
```

FWIW for the large file this library is about 2x faster than fast-json-stable-stringify.

I had tried some tricks, like cloning objects sometimes is unnecessary if they are already sorted, but that didn't seem to make a big difference.
